# Generated by Django 6.0.6 on 2026-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="icon_emoji",
            field=models.CharField(
                default="📚", help_text="Emoji icon for the course.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to a course thumbnail image (e.g. from Unsplash).",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, default="", help_text="URL to a lesson thumbnail image."
            ),
        ),
    ]
